
module.exports = {
  'margin': 'm',
  'margin-top': 'mt',
  'margin-right': 'mr',
  'margin-bottom': 'mb',
  'margin-left': 'ml',
  'padding': 'p',
  'padding-top': 'pt',
  'padding-right': 'pr',
  'padding-bottom': 'pb',
  'padding-left': 'pl',
  'font-family': 'ff',
  'font-size': 'fs',
  'font-weight': 'fw',
  'line-height': 'lh',
  'display': 'd',
  'height': 'h',
  'width': 'w',
  'min-width': 'minw',
  'max-width': 'maxw',
  'min-height': 'minh',
  'max-height': 'maxh',
  'position': 'pos',
  'background-color': 'bg',
  'background-image': 'bg-img',
  'z-index': 'z',
}

